import fs from "fs";
import path from "path";

const master = JSON.parse(fs.readFileSync("data/master/master-matrix.json","utf8"));

fs.mkdirSync("generated", { recursive: true });

// 1) equivalency matrix
fs.writeFileSync("generated/equivalency.generated.json", JSON.stringify({
  catalog_version: master.catalog_version,
  generated_at: new Date().toISOString(),
  rows: master.rows.map(r => ({
    domain: r.domain,
    capability_id: r.capability_id,
    capability_name: r.capability_name,
    used_for: r.used_for,
    providers: r.providers
  }))
}, null, 2));

// 2) per-provider inventory
const providers = ["aws","azure","gcp","oci"];
for(const p of providers){
  const seen = new Map(); // service -> {service, capabilities:[]}
  for(const r of master.rows){
    const svcs = (r.providers?.[p] || []).filter(Boolean);
    for(const s of svcs){
      const key = s.trim();
      if(!key || key === "—") continue;
      if(!seen.has(key)){
        seen.set(key, { service: key, capabilities: [], domains: new Set() });
      }
      seen.get(key).capabilities.push(r.capability_id);
      seen.get(key).domains.add(r.domain);
    }
  }
  const out = Array.from(seen.values()).map(x => ({
    service: x.service,
    domains: Array.from(x.domains),
    capabilities: Array.from(new Set(x.capabilities))
  })).sort((a,b)=>a.service.localeCompare(b.service));
  fs.writeFileSync(`generated/${p}.services.generated.json`, JSON.stringify({
    provider: p,
    catalog_version: master.catalog_version,
    generated_at: new Date().toISOString(),
    services: out
  }, null, 2));
}

// 3) browser bundle
const bundle = {
  catalog_version: master.catalog_version,
  generated_at: new Date().toISOString(),
  rows: master.rows
};

const js = `// Auto-generated by ATK build.mjs
window.ATK_CATALOG = ${JSON.stringify(bundle, null, 2)};
`;
fs.writeFileSync("generated/catalog.generated.js", js);

const versionJs = `window.ATK_VERSION = ${JSON.stringify({
  catalog_version: master.catalog_version,
  generated_at: new Date().toISOString()
}, null, 2)};\n`;
fs.writeFileSync("generated/version.generated.js", versionJs);

console.log("Build completed. Outputs in /generated");
