import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// ✅ Correct ESM path handling (Windows-safe)
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

const masterPath = path.join(
  repoRoot,
  "data",
  "master",
  "master-matrix.json"
);

const outDir = path.join(repoRoot, "web", "generated");
fs.mkdirSync(outDir, { recursive: true });

const master = JSON.parse(fs.readFileSync(masterPath, "utf8"));

function makeProvider(providerId, displayName) {
  const serviceCategories = {};

  for (const row of master.rows) {
    const cat = row.domain;
    const services = (row.providers?.[providerId] || []).map((name) => ({
      id: (providerId + "_" + name)
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "_")
        .replace(/^_+|_+$/g, ""),
      name,
      category: cat
    }));

    serviceCategories[cat] = services;
  }

  return { id: providerId, displayName, serviceCategories };
}

const catalog = {
  version: master.catalog_version,
  generatedAt: new Date().toISOString(),
  providers: {
    aws: makeProvider("aws", "AWS"),
    azure: makeProvider("azure", "Azure"),
    gcp: makeProvider("gcp", "Google Cloud"),
    oci: makeProvider("oci", "Oracle Cloud")
  }
};

const js = `// Auto-generated by scripts/build.mjs
(function(){
  window.CDK = window.CDK || { providers: {}, tools: {} };
  window.CDK.providers = window.CDK.providers || {};
  const catalog = ${JSON.stringify(catalog, null, 2)};
  window.ATK_CATALOG = catalog;
  window.CDK.providers.aws = catalog.providers.aws;
  window.CDK.providers.azure = catalog.providers.azure;
  window.CDK.providers.gcp = catalog.providers.gcp;
  window.CDK.providers.oci = catalog.providers.oci;
})();`;

fs.writeFileSync(
  path.join(outDir, "catalog.generated.js"),
  js,
  "utf8"
);

fs.writeFileSync(
  path.join(outDir, "version.generated.js"),
  `window.ATK_VERSION=${JSON.stringify({
    version: master.catalog_version,
    generatedAt: catalog.generatedAt
  })};\n`,
  "utf8"
);

// --- ADD THIS BLOCK TO scripts/build.mjs (near the end) ---
const decisionDir = path.join(repoRoot, "data", "decision");
const decisionOut = path.join(outDir, "decision.generated.js");

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

const decision = {
  generatedAt: new Date().toISOString(),
  capabilities: readJson(path.join(decisionDir, "capabilities.json")),
  patterns: readJson(path.join(decisionDir, "patterns.json")),
  rules: readJson(path.join(decisionDir, "rules.json"))
};

const decisionJs = `// Auto-generated by scripts/build.mjs
(function(){
  window.ATK_DECISION = ${JSON.stringify(decision, null, 2)};
})();`;

fs.writeFileSync(decisionOut, decisionJs, "utf8");
console.log("✅ Built web/generated/decision.generated.js");
